---
# tasks file for roles/keywoo
- name: Clone keywoo repository
  git:
    repo: 'https://github.com/ymmmtym/keywoo.git'
    dest: keywoo
    clone: yes
    update: yes
    version: '{{ version }}'

- name: docker compose up
  docker_compose:
    project_src: keywoo
    state: present
  become: yes